name: flutter_web_router_example
description: Demonstrates how to use the flutter_web_router plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_router:
    path: ../

  cupertino_icons: ^1.0.0
  flutter_admin_scaffold: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

